version: "3.7"

services:
  mzpc-mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: mzpc
    ports:
      - 3307:3306

volumes:
  todo-mysql-data: