
#Server

server:
  port: 9010
  servlet:
    session:
      timeout: 360000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mzpc
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    s3:
      bucket: mzpc-s3-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA6HZPM5DTOATITDU4
      secret-key: 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

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

logging:
  level:
    com:
      fivemin: DEBUG

# email
mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

AdminMail:
  id: kts3445@gmail.com
  password: cyejgurdyssgsgsv

