
#Server

server:
  port: 9010
  servlet:
    session:
      timeout: 360000

spring:
  session:
    store-type: redis
    redis:
      host: localhost
      port: 6380
      password : 1234

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  datasource:
    url: jdbc:mysql://localhost:3307/mzpc
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

logging:
  level:
    com:
      fivemin: DEBUG

# email

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

AdminMail:
  id: kts3445@gmail.com
  password: cyejgurdyssgsgsv